name: automerge pull requests

on:
  pull_request:
    types: [labeled]

jobs:

  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const label = pullRequest.labels.find(label => label.name === 'invalid');
            if (label) {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });
            }


with: 
  message: "Your PR has been merged. Thank you for your contribution to the project. :tada:"
